package app

var mainSQLitePragmas = []string{
	"PRAGMA journal_mode=WAL;",
	"PRAGMA synchronous=NORMAL;",
	"PRAGMA busy_timeout=5000;",
	"PRAGMA foreign_keys=ON;",
}

var mainSQLiteSchemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS packet_events (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		captured_at TEXT NOT NULL DEFAULT (datetime('now')),
		capture_id INTEGER,
		event_timestamp REAL,
		src_ip TEXT,
		dst_ip TEXT,
		proto TEXT,
		length INTEGER,
		is_threat INTEGER,
		threat_type TEXT,
		reason TEXT,
		summary TEXT,
		firewall_action TEXT,
		packet_details_json TEXT,
		analysis_json TEXT,
		raw_json TEXT NOT NULL
	);`,
	`CREATE INDEX IF NOT EXISTS idx_packet_events_captured_at ON packet_events(captured_at);`,
	`CREATE INDEX IF NOT EXISTS idx_packet_events_is_threat ON packet_events(is_threat);`,
	`CREATE INDEX IF NOT EXISTS idx_packet_events_src_ip ON packet_events(src_ip);`,
	`CREATE INDEX IF NOT EXISTS idx_packet_events_dst_ip ON packet_events(dst_ip);`,
	`CREATE TABLE IF NOT EXISTS behavior_sessions (
		session_id TEXT PRIMARY KEY,
		first_seen TEXT NOT NULL DEFAULT (datetime('now')),
		last_seen TEXT NOT NULL DEFAULT (datetime('now')),
		start_time TEXT,
		duration TEXT,
		main_service TEXT,
		main_domain TEXT,
		behavior_label TEXT,
		risk_score INTEGER,
		risk_level TEXT,
		request_count INTEGER,
		behavior_chain_json TEXT,
		requests_json TEXT,
		raw_json TEXT NOT NULL
	);`,
	`CREATE INDEX IF NOT EXISTS idx_behavior_sessions_last_seen ON behavior_sessions(last_seen);`,
	`CREATE INDEX IF NOT EXISTS idx_behavior_sessions_risk_level ON behavior_sessions(risk_level);`,
	`CREATE TABLE IF NOT EXISTS lan_behavior_reports (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		captured_at TEXT NOT NULL DEFAULT (datetime('now')),
		ip_address TEXT NOT NULL,
		first_seen TEXT,
		last_seen TEXT,
		duration TEXT,
		total_requests INTEGER,
		total_bytes_sent TEXT,
		total_bytes_received TEXT,
		unique_domains INTEGER,
		risk_score INTEGER,
		risk_level TEXT,
		top_domains_json TEXT,
		category_stats_json TEXT,
		risk_events_json TEXT,
		raw_json TEXT NOT NULL
	);`,
	`CREATE INDEX IF NOT EXISTS idx_lan_behavior_ip ON lan_behavior_reports(ip_address);`,
	`CREATE INDEX IF NOT EXISTS idx_lan_behavior_captured_at ON lan_behavior_reports(captured_at);`,
	`CREATE INDEX IF NOT EXISTS idx_lan_behavior_risk_level ON lan_behavior_reports(risk_level);`,
	`CREATE TABLE IF NOT EXISTS ingest_logs (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		created_at TEXT NOT NULL DEFAULT (datetime('now')),
		source TEXT NOT NULL,
		level TEXT,
		message TEXT,
		raw_text TEXT
	);`,
	`CREATE INDEX IF NOT EXISTS idx_ingest_logs_created_at ON ingest_logs(created_at);`,
	`CREATE TABLE IF NOT EXISTS web_access_logs (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		captured_at TEXT NOT NULL DEFAULT (datetime('now')),
		src_ip TEXT,
		dst_ip TEXT,
		domain TEXT,
		full_host TEXT,
		category TEXT,
		app_name TEXT,
		bytes INTEGER NOT NULL DEFAULT 0,
		request_count INTEGER NOT NULL DEFAULT 0,
		evidence_level TEXT,
		raw_json TEXT
	);`,
	`CREATE INDEX IF NOT EXISTS idx_web_access_logs_captured_at ON web_access_logs(captured_at);`,
	`CREATE INDEX IF NOT EXISTS idx_web_access_logs_src_ip ON web_access_logs(src_ip);`,
	`CREATE INDEX IF NOT EXISTS idx_web_access_logs_domain ON web_access_logs(domain);`,
	`CREATE TABLE IF NOT EXISTS search_audit_logs (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		captured_at TEXT NOT NULL DEFAULT (datetime('now')),
		src_ip TEXT,
		domain TEXT,
		engine TEXT,
		keyword TEXT,
		evidence_level TEXT,
		raw_json TEXT
	);`,
	`CREATE INDEX IF NOT EXISTS idx_search_audit_logs_captured_at ON search_audit_logs(captured_at);`,
	`CREATE INDEX IF NOT EXISTS idx_search_audit_logs_src_ip ON search_audit_logs(src_ip);`,
	`CREATE INDEX IF NOT EXISTS idx_search_audit_logs_domain ON search_audit_logs(domain);`,
	`CREATE TABLE IF NOT EXISTS violation_events (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		captured_at TEXT NOT NULL DEFAULT (datetime('now')),
		src_ip TEXT,
		domain TEXT,
		violation_type TEXT,
		severity TEXT,
		reason TEXT,
		raw_json TEXT
	);`,
	`CREATE INDEX IF NOT EXISTS idx_violation_events_captured_at ON violation_events(captured_at);`,
	`CREATE INDEX IF NOT EXISTS idx_violation_events_src_ip ON violation_events(src_ip);`,
	`CREATE INDEX IF NOT EXISTS idx_violation_events_domain ON violation_events(domain);`,
	`CREATE INDEX IF NOT EXISTS idx_violation_events_type ON violation_events(violation_type);`,
	`CREATE TABLE IF NOT EXISTS report_exports (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		report_type TEXT NOT NULL,
		period_start TEXT NOT NULL,
		period_end TEXT NOT NULL,
		file_path TEXT NOT NULL,
		created_at TEXT NOT NULL DEFAULT (datetime('now')),
		summary_json TEXT
	);`,
	`CREATE INDEX IF NOT EXISTS idx_report_exports_created_at ON report_exports(created_at);`,
	`CREATE INDEX IF NOT EXISTS idx_report_exports_type ON report_exports(report_type);`,
	`CREATE TABLE IF NOT EXISTS managed_tasks (
		task_name TEXT PRIMARY KEY,
		desired_state TEXT NOT NULL DEFAULT 'stopped',
		runtime_status TEXT NOT NULL DEFAULT 'idle',
		auto_restart INTEGER NOT NULL DEFAULT 1,
		command_json TEXT,
		args_json TEXT,
		started_at TEXT,
		stopped_at TEXT,
		updated_at TEXT NOT NULL DEFAULT (datetime('now')),
		last_exit_at TEXT,
		last_exit_reason TEXT,
		restart_count INTEGER NOT NULL DEFAULT 0,
		consecutive_failures INTEGER NOT NULL DEFAULT 0,
		next_restart_at TEXT,
		last_error TEXT
	);`,
}
